# Generated by Django 4.2 on 2024-01-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0002_alter_module_credit_alter_module_name'),
        ('users', '0004_rename_city_student_citytown'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stuCourse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itreporting.course'),
        ),
    ]
