# Generated by Django 4.2 on 2024-01-16 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('name', models.CharField(max_length=15, primary_key='name', serialize=False)),
                ('code', models.CharField(max_length=9)),
                ('credit', models.IntegerField(choices=[('20', '20'), ('40', '40'), ('60', '60')], max_length=2)),
                ('category', models.TextField(choices=[('Compulsory', 'Compulsory'), ('Elective', 'Elective')], max_length=10)),
                ('description', models.TextField(max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('coursesAllowed', models.ManyToManyField(to='itreporting.course')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegistered', models.DateTimeField(default=django.utils.timezone.now)),
                ('module', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='itreporting.module')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
