# Generated by Django 4.2 on 2024-01-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='credit',
            field=models.IntegerField(choices=[(20, '20'), (40, '40'), (60, '60')]),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50, primary_key='name', serialize=False),
        ),
    ]
